name: Java Maven CI/CD Pipeline

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for SonarCloud analysis

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B clean package

    - name: Run Tests with Coverage
      run: mvn -B jacoco:report

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=ramsnow42_arrangementmanager
          -Dsonar.organization=ramsnow42key  # Replace with your actual org key
          -Dsonar.projectName=arrangement-manager
          -Dsonar.java.binaries=target/classes
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
          -Dsonar.ci.autoconfig.disabled=true  # Add this line
          -Dsonar.ci.skipAutoconfig=true
          -Dsonar.analysis.ci=false
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.branch.name=main
          -Dsonar.scm.provider=git

  build-and-push:
    needs: build-test-scan
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Using password instead of token
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}  # Using token instead of password

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/arrangement-manager:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/arrangement-manager:${{ github.sha }}
        platforms: linux/amd64
        build-args: |
          APP_VERSION=${{ github.sha }}